Detect both and libSDL and libSDL-1.2
libSDL-1.2 seems to be needed on amd64 Debian/sid while libSDL is
needed on i386 Debian/sid. Let's not care.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4380,20 +4380,85 @@ cat >>confdefs.h <<\_ACEOF
 #define HAVE_SDL 1
 _ACEOF
 
+		LIBSDL="-lSDL"
+
+fi
+
+	{ echo "$as_me:$LINENO: checking for SDL_Init in -lSDL-1.2" >&5
+echo $ECHO_N "checking for SDL_Init in -lSDL-1.2... $ECHO_C" >&6; }
+if test "${ac_cv_lib_SDL_1_2_SDL_Init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lSDL-1.2  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char SDL_Init ();
+int
+main ()
+{
+return SDL_Init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_SDL_1_2_SDL_Init=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_SDL_1_2_SDL_Init=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_SDL_1_2_SDL_Init" >&5
+echo "${ECHO_T}$ac_cv_lib_SDL_1_2_SDL_Init" >&6; }
+if test $ac_cv_lib_SDL_1_2_SDL_Init = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SDL 1
+_ACEOF
+
+		LIBSDL="-lSDL-1.2"
+
 fi
 
 fi
 
 done
 
-if test "$ac_cv_lib_SDL_SDL_Init" = "yes"
-then
-	LIBSDL="-lSDL"
-
-else
-	LIBSDL=""
-
-fi
 
 for ac_prog in i686-pc-mingw32-gcc i586-mingw32msvc-cc no
 do
@@ -6000,8 +6065,8 @@ then
 echo "$as_me: WARNING: libxml2 development libraries not present (Debian package is libxml2-dev)" >&2;}
 fi
 
-if test "$ac_cv_lib_SDL_SDL_Init" != "yes" -o \
-	"$ac_cv_header_SDL_SDL_h" != "yes"
+if test "$ac_cv_lib_SDL_1_2_SDL_Init" != "yes" -a \
+	"$ac_cv_lib_SDL_SDL_Init" != "yes"
 then
 	{ echo "$as_me:$LINENO: WARNING: libSDL development libraries not present (Debian package is libsdl1.2-dev)" >&5
 echo "$as_me: WARNING: libSDL development libraries not present (Debian package is libsdl1.2-dev)" >&2;}
